import os
os.mkdir("Testing OS")
print(os.getcwd())
print(os.listdir("Testing OS"))
print(os.listdir())
os.rename("Testing OS","Testing OSRename")
os.chdir("Testing OSRename")
open("OS handling.txt","w+")
print(os.listdir())
os.mkdir("RenameDir")
os.chdir("RenameDir")
open("Testing Renames.txt","w+")
os.chdir("../")
print(os.listdir())
os.chdir("../")
os.renames("Testing OSRename","./test2/testing")
print(os.path.isdir("test2"))   
print(os.path.getsize("Java"))
print(os.path.getsize("Java/Animals"))